# Generated by Django 2.2.1 on 2019-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190521_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tel',
            field=models.CharField(default=0, max_length=200, verbose_name='用户电话'),
        ),
    ]
