# Generated by Django 2.2.1 on 2019-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190521_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tel',
        ),
        migrations.AddField(
            model_name='myuser',
            name='url',
            field=models.URLField(blank=True, default='http://baidu.com', null=True),
        ),
    ]
